"""Promote acquisition-native tile geometry and biological cross-assay validations
to top of Map10 page. Private per-cell remains private.
"""
from pathlib import Path
import re
P=Path(r"G:\Spatial_gene_site_publish\perilc-map6-review");F=P/"single-cell.html";h=F.read_text(encoding="utf8")
def card(title,rel,desc):
 assert (P/rel).is_file(),rel
 return f'<article class="card"><h3>{title}</h3><a href="{rel}"><img loading="lazy" src="{rel}" alt="{title}"></a><p>{desc}</p></article>'
r="assets/stage1018_acquisition_tile_overlaps/";c="assets/stage1017_segmentation_confounds/"
a="assets/stage1015_scrna_gaba_glu/";allen="assets/stage1016_allen_pons/";adj="assets/stage1019_edge_adjusted/"
figs=[
card("REAL acquisition tile overlap geometry · VGAT>10 VGLUT2>3",r+"STAGE1018_VGAT10_GLU3_NATIVE_TILE_OVERLAP_SPATIAL.png","All 71,950 cell centers S500/S530/S560. Native 25 tile starts from each section stitching/tiles.json, mapped via individually validated Stage631 array-pixel affine; green bands = original tile overlap strips, dashed lines = strip midline, not exact optimizer pixel fusion seam."),
card("True tile overlap: measured double-positive rates",r+"STAGE1018_NATIVE_TILE_ENRICHMENT_BY_SECTION_AND_THRESHOLD.png","Primary reference-neuron VGAT>10/GLU>3: S500 overlap 26.97% vs outside 25.27%; S530 22.26% vs 25.87%; S560 21.45% vs 21.85%. No reproducible direction across the three slices of one specimen."),
card("Control for soma size, 27-gene count and Frozen Fine26",adj+"STAGE1019_TILE_SEAM_ADJUSTED_FOR_CELL_SIZE_AND_DEPTH.png","Pooled native-tile overlap crude difference −0.35 percentage points; adjusted for soma area+gene count+section −0.44 pp; plus Fine26 +0.37 pp. Descriptive association only; 27-gene total is outcome-contaminated denominator."),
card("Cell segmentation area, depth and nearest opposing-marker cells",c+"STAGE1017_DUAL_MARKER_SEGMENTATION_DEPTH_NEIGHBOR_QC.png","Dual positivity correlates strongly with larger segmented soma area (Spearman r≈0.499) and total27 gene counts (r≈0.555), but weakly with proximity to opposite-only cells. Correlation not proof of segmentation error."),
card("Each frozen Fine26 × section: dual-positive fraction",c+"STAGE1017_FINE26_DUAL_POSITIVE_PER_SECTION.png","Intra-class and section variation; Fine26 labels partially constructed using transmitter genes and cannot be a fully independent biological validation."),
card("Rong own scRNA: 4,701 neurons and 25 frozen clusters",a+"STAGE1015_RONG_25CLUSTER_GABA_GLU_DOUBLE_RAW_UMI.png","Direct scRNA counts-layer raw UMI: Slc32a1/Slc17a6 both detected 73/4701=1.55%. Both >1 UMI: zero; Gad1/2 and VGLUT1/2/3 family dual gene detection 7.81%. RNA UMI dropout not comparable to FISH corrected spots."),
card("Rong scRNA: raw-UMI depth dependence",a+"STAGE1015_RONG_DOUBLE_UMI_DEPTH_QC.png","Shows why deeper transcript detection can raise observed double positives without implying co-release."),
card("Allen Pons WMB-10Xv3 original raw UMI",allen+"STAGE1016_ALLEN_PONS_SLC32A1_SLC17A6_RAW_UMI.png","143,661 Allen Pons transcriptomes: any Slc32a1 and Slc17a6 raw UMI detected 1,832=1.28%; Snap25-detected 72,503 cells: 1,768=2.44%. Different assay modalities and anatomical populations."),
card("Raw-FISH two-marker strict comparator",r+"STAGE1018_VGAT10_GLU10_NATIVE_TILE_OVERLAP_SPATIAL.png","VGAT>10, VGLUT2>10, no normalized-denominator artifacts."),
card("Raw-FISH gene-dependent comparator",r+"STAGE1018_VGAT15_GLU5_NATIVE_TILE_OVERLAP_SPATIAL.png","VGAT>15 VGLUT2>5; native tile overlaps included."),
]
src='<section id="stage1018-real-tile-and-reference"><h2>VGAT/VGLUT2 co-expression: original tile metadata, cell-morphology confounds, own scRNA and Allen</h2><p class="lead"><strong>Direct tests completed.</strong> Stage1018 reads S500/S530/S560 native 25-tile stitching/tiles.json and maps overlapping tile acquisition footprints through section-specific Stage631 physical affine (X and Y already flipped). The older Stage1014 equally spaced phase-zero grid is a historical sensitivity check, <b>not the authoritative tile geometry</b>. The actual optimizer fusion cut may be within the original overlap strip, so the overlap zone, midline±8, ±15, ±25µm were compared.</p><p class="lead">With VGAT corrected count &gt;10 and VGLUT2 &gt;3, among 68,572 reference neurons: S500 <b>26.97% near vs 25.27% away</b>, S530 <b>22.26% vs 25.87%</b>, S560 <b>21.45% vs 21.85%</b>. Not consistent tile-edge enrichment. Cell mask area (Spearman rho 0.499) and total measured gene count (rho 0.555) have MUCH stronger associations with dual positivity, while local opposite-marker cell mixing is weak. The measurement model, mask volume, and ambient puncta demand further audit before claiming genuine cotransmission or segmentation artifacts. Both VGAT/Glu normalized P70 and low raw count cutoffs have assay-dependent background.</p><p class="lead"><strong>Independent transcriptome comparators are now quantitative:</strong> Own Rong 4,701 frozen 25-cluster neurons: 73 two-gene detectable (1.55%); Allen Pons 143,661 10Xv3 cells: 1,832 (1.28%). Allen Pons Snap25 detected only: 1,768/72,503 (2.44%). These are raw scRNA UMI and <b>must not be compared quantitatively as if equivalent to EASI-FISH corrected spot counts</b>. The own first- and second-round sample-mix matrices are tracked separately.</p><div class="cards">'+''.join(figs)+'</div><p class="lead">Download methodology and aggregate QA: <a href="data/stage1018_native_tile_overlap_dual_rates.csv">native tile edge count/risk tables</a>, <a href="data/stage1018_tile_geometry_and_Stage631_affines.csv">measured per-section geometry</a>, <a href="data/stage1019_tile_seam_size_depth_adjusted_association.csv">area/depth/section/identity adjusted associations</a>, <a href="data/stage1017_fine26_section_double_positive_confounds.csv">Fine26 per-section co-detection</a>, <a href="data/stage1015_Rong_4701_cluster25_GABA_GLU_rawUMI_sensitivity.csv">Rong scRNA raw-UMI sweep</a>, <a href="data/stage1016_allen_pons_GABA_GLU_rawUMI_threshold_sweep.csv">Allen Pons raw-UMI sweep</a>, and <a href="data/stage1018_native_tile_seam_authority.json">tile-source limitations</a>. No per-cell molecular coordinates are published.</p></section>'
if 'id="stage1018-real-tile-and-reference"' not in h:
 assert '<section id="stage1014-dual-spatial">' in h
 h=h.replace('<section id="stage1014-dual-spatial">',src+'<section id="stage1014-dual-spatial">',1)
 h=h.replace('<a href="#stage1014-dual-spatial">','<a href="#stage1018-real-tile-and-reference">Real tile overlap + scRNA + Allen</a><a href="#stage1014-dual-spatial">',1)
assert all((P/x).exists() for x in re.findall(r'<img[^>]+src="([^"]+)"',h) if x.startswith("assets/"))
F.write_text(h,encoding="utf8")
print("STAGE1021_PUBLIC_PAGE_READY",len(h),h.count('id="stage1018-real-tile-and-reference"'))
